### PR TITLE
feat(Site): alerts for version upgrades and site migrations

### PR DESCRIPTION
**Pull request by BreadGenie**
image

image

### CODE REVIEW

**Comment by BreadGenie** [comment]
Might stick with just alerts for scheduled and running upgrades/migrations. Failed upgrades/migrations can be a notification and maybe same goes for successful upgrades/migrations

**Comment by michellealva** [comment]
@BreadGenie use the same font case for both.

**Comment by BreadGenie** [comment]
> @BreadGenie use the same font case for both.

Both the alerts have the default font though. Might be the length of the text that's making it look different?

**Comment by michellealva** [comment]
I mean use consistent capitalisation of words

**Comment by NagariaHussain** [comment]
The first one is sentence case (only T is capital), while the second is mixed case.

**Pull request merged**
