### PR TITLE
style(BenchAppUpdate): redesign dropdown of commits

### LINKED ISSUE #1095: alignment issue because of version dropdown
image

### PR DESCRIPTION
**Pull request by BreadGenie**
fix #1095

### Before
image

### After
image

### CODE REVIEW

**Comment by adityahase** [comment]
LGTML

**Comment by NagariaHussain** [comment]
Can we show commit messages too in the drop down? 

Human readable 😅

**Comment by BreadGenie** [comment]
image

Is this fine?

**Comment by NagariaHussain** [comment]
> image
> 
> 
> 
> Is this fine?

Looks good 👍, make sure you handle too long messages (ellipses maybe)...

**Comment by ankush** [comment]
Commit messages can ne ignored for tagged releases. They'll be generic "chore release X"

**Pull request merged**
