### PR TITLE
feat: allow users to refresh stripe payment url

### PR DESCRIPTION
**Pull request by shadrak98**
Use "Pay Now" button to refresh expired link.

Screenshot 2023-06-27 at 2 45 49 PM

fixes https://github.com/frappe/press/issues/828

### CODE REVIEW

**Comment by shadrak98** [comment]
@rutwikhdev can you check the placement of the refresh link button? It looked weird side-by-side.

**Comment by BreadGenie** [comment]
@shadrak98 maybe just the refresh icon on the right of Pay Now button with "Refresh Payment Link" as tooltip would look better.
Also if the payment link is expired maybe the Pay Now button can be greyed out (disabled).

**Comment by rutwikhdev** [comment]
> @shadrak98 maybe just the refresh icon on the right
You can also show "Refresh Payment Link" on hover for icon

**Review by BreadGenie — APPROVED** [review]
LGTM

**Pull request merged**
